version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  database: # name of the first service (database)
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding
    volumes:
      - ./db:/data/db
      
  express: #name of the second service (back)
    build: backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    depends_on:
       - "database" #starts after database service
    links:
      - database

  angular: # name of the third service (front)
    build: ./frontend # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
      - "49153:49153"
    depends_on:
      - "express" #starts after express service
    volumes:
      - ./frontend:/frontend # this will enable changes made to the angular app reflect in the container