version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  database: # name of the first service (database)
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding
    volumes:
      - ./db:/data/db
      - ./initdb:/docker-entrypoint-initdb.d:ro #Stop with docker container ls and then docker container stop <id>
    #Disable logs
    command: mongod --quiet --logpath /dev/null
    env_file: .env
      
  express: #name of the second service (back)
    build: backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forwarding
    depends_on:
      - "database" #starts after database service
    volumes:
      - ./backend:/backend
    links:
      - database
    env_file:
      - .env

  angular: # name of the third service (front)
    build: ./frontend # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
      - "9876:9876"
    depends_on:
      - "express" #starts after express service
    volumes:
      - ./frontend:/frontend # this will enable changes made to the angular app reflect in the container
      - ./imgs:/imgs #Redirect imgs local folder to imgs docker folder

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "angular"
    volumes:
      - ./frontend:/www/Angular11/