name: AVA backend test

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs: {}

jobs:
  test:
    name: "Build and test the backend"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Angular11/backend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: "Install nodejs"
        run: npm ci
      #- run: npm run build --if-present
      - name: "Run test"
        run: npm test
